spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/app_template?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: root

server:
    port: 8090

customize:
    log:
        path: ./
        name: app-template